{% set name = "conda-souschef" %}
{% set version = "1.1.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/conda-souschef-{{ version }}.tar.gz
  sha256: 35abd4493b81c71499dea50a3478669e4809b58f7ca4ec7a37ad85d15d3bc353

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools >=30.3.0
    - setuptools-scm
  run:
    - python >=3.8
    - ruamel.yaml >=0.15.3
    - ruamel.yaml.jinja2

test:
  imports:
    - souschef
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/marcelotrevisani/souschef
  summary: Project to handle conda recipes
  dev_url: https://github.com/marcelotrevisani/souschef
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - marcelotrevisani
